# Soong Override
OVERRIDE_QCOM_HARDWARE_VARIANT := sm6225
QCOM_SOONG_NAMESPACE := hardware/qcom-caf/sm6225
TARGET_HALS_PATH ?= $(QCOM_SOONG_NAMESPACE)

# Audio
USE_DEVICE_SPECIFIC_AUDIO := true
DEVICE_SPECIFIC_AUDIO_PATH := $(TARGET_HALS_PATH)/audio

# Display
USE_DEVICE_SPECIFIC_DISPLAY := true
DEVICE_SPECIFIC_DISPLAY_PATH := $(TARGET_HALS_PATH)/display

# Media
USE_DEVICE_SPECIFIC_MEDIA := true
DEVICE_SPECIFIC_MEDIA_PATH := $(TARGET_HALS_PATH)/media
